### ISSUE TITLE
Issue with callback within restify

### ISSUE THREAD

**Issue by vincentjames501** [danieltdt/node-json-rest-client#2]
When using this library, I believe there is an issue with the ```performRequest``` function just haven't had the time to diagnose why.

```javascript
var assert = require('assert');

function ICMClient(config) {
    assert(config, 'Config object must be present');
    assert(config.token, 'Token must be present in config');

    var rest = require('json-rest-client')({
        url: config.url
    }, {
        headers: {
            'X-Client-Version': 'NodejsClient 0.0.1',
            'Authorization': 'Bearer ' + config.token
        }
    });

    return {
        users: rest.resource('/api/v1-DEV/users')
    };
}

//url and token have been removed
var client = ICMClient({url: 'myapiurl', token: 'mytoken'});

var users = client.users().all();

module.exports = ICMClient;
```

Produces the following stacktrace:

```
/Users/vincent/WebstormProjects/icm-nodejs-client/node_modules/json-rest-client/node_modules/restify/lib/clients/json_client.js:84
        callback((err || null), req2, res, obj);
        ^
TypeError: undefined is not a function
    at parseResponse (/Users/vincent/WebstormProjects/icm-nodejs-client/node_modules/json-rest-client/node_modules/restify/lib/clients/json_client.js:84:9)
    at IncomingMessage.done (/Users/vincent/WebstormProjects/icm-nodejs-client/node_modules/json-rest-client/node_modules/restify/lib/clients/string_client.js:151:17)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by danieltdt** [comment]
Hmm I'll check this out later today.
On Jan 7, 2015 12:43 AM, "Vincent Pizzo" <notifications@github.com> wrote:

When using this library, I believe there is an issue with the performRequest
function just haven't had the time to diagnose why.

var assert = require('assert');
function ICMClient(config) {
    assert(config, 'Config object must be present');
    assert(config.token, 'Token must be present in config');

    var rest = require('json-rest-client')({
        url: config.url
    }, {
        headers: {
            'X-Client-Version': 'NodejsClient 0.0.1',
            'Authorization': 'Bearer ' + config.token
        }
    });

    return {
        users: rest.resource('/api/v1-DEV/users')
    };
}
//url and token have been removedvar client = ICMClient({url:
'myapiurl', token: 'mytoken'});
var users = client.users().all();
module.exports = ICMClient;

Produces the following stacktrace:

/Users/vincent/WebstormProjects/icm-nodejs-client/node_modules/json-rest-client/node_modules/restify/lib/clients/json_client.js:84
        callback((err || null), req2, res, obj);
        ^
TypeError: undefined is not a function
    at parseResponse
(/Users/vincent/WebstormProjects/icm-nodejs-client/node_modules/json-rest-client/node_modules/restify/lib/clients/json_client.js:84:9)
    at IncomingMessage.done
(/Users/vincent/WebstormProjects/icm-nodejs-client/node_modules/json-rest-client/node_modules/restify/lib/clients/string_client.js:151:17)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

—
Reply to this email directly or view it on GitHub
<https://github.com/danieltdt/node-json-rest-client/issues/2>.
